name: "AElf Proposal Details Action"
description: "Fetches the proposal details"
inputs:
  proposal-id:
    description: "Proposal ID"
    required: true
  node-url:
    description: "AElf Blockchain node url"
    required: true
    default: "https://tdvw-test-node.aelf.io"
  explorer-url:
    description: "AElf Explorer url"
    required: true
    default: "https://explorer-test-side02.aelf.io"
outputs:
  create-tx-id:
    description: "The transaction id of the create proposal transaction."
  is-contract-deployed:
    description: "Whether the contract is deployed"
  proposal-type:
    description: "Type of proposal."
  proposer:
    description: "AElf Address of the proposer."
  released-tx-id:
    description: "The transaction id of the release proposal transaction."
  status:
    description: "Status of the proposal."
runs:
  using: "node20"
  main: "dist/index.js"
